### ISSUE TITLE
How to run the demo?

### ISSUE THREAD

**Issue by seanwl** [eclipse/titan.ProtocolModules.DNS#1]
I was new to ttcn language, just install titan.core and successfully executed the simple system port test on this page https://github.com/eclipse/titan.core/wiki/Simple-TTCN3-Examples, and I planed to run a dns test, but failed many times.
In the result of compiling your demo code, first its said 

> DNS_Mapping.ttcn:22.1-28: error: There is no module with identifier `UDPasp_Types'

then I copy the files in your titan.TestPorts.UDPasp  src page into demo folders and the error is corrected, but came up with a bunch of new errors, states below,

> if g++   -o DNS_Demo DNS_Demo.o DNS_Mapping.o DNS_Types.o UDPasp_PortType.o UDPasp_Types.o  \
> -L/home/seanwl/titan.core/Install/lib -lttcn3 \
> -L/lib -lcrypto \
> -L/home/seanwl/titan.core/Install/lib -lxml2; \
> then : ; else /home/seanwl/titan.core/Install/bin/titanver DNS_Demo.o DNS_Mapping.o DNS_Types.o UDPasp_PortType.o UDPasp_Types.o ; exit 1; fi
> DNS_Mapping.o: In function `DNS__Mapping::f__DNS__mapping__behaviour()':
> DNS_Mapping.cc:(.text+0x6c02): undefined reference to `DNS__Types::dec__PDU__DNS(OCTETSTRING const&)'
> DNS_Mapping.cc:(.text+0x6e1a): undefined reference to `DNS__Types::enc__PDU__DNS(DNS__Types::PDU__DNS const&, BOOLEAN const&, BOOLEAN const&)'
> DNS_Types.o: In function `DNS__Types::pre_init_module()':
> DNS_Types.cc:(.text+0x43144): undefined reference to `DNS__Types::enc__PDU__DNS(DNS__Types::PDU__DNS const&, BOOLEAN const&, BOOLEAN const&)'
> DNS_Types.cc:(.text+0x43166): undefined reference to `DNS__Types::dec__PDU__DNS(OCTETSTRING const&)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::UDPasp__PT(char const*)':
> UDPasp_PortType.cc:(.text+0x229): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::UDPasp__PT_PROVIDER(char const*)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::~UDPasp__PT()':
> UDPasp_PortType.cc:(.text+0x2a2): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::~UDPasp__PT_PROVIDER()'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::send(UDPasp__Types::ASP__UDP__open const&, COMPONENT const&, FLOAT*)':
> UDPasp_PortType.cc:(.text+0x412): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__open const&)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::send(UDPasp__Types::ASP__UDP__close const&, COMPONENT const&, FLOAT*)':
> UDPasp_PortType.cc:(.text+0x7e2): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__close const&)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::send(UDPasp__Types::ASP__UDP const&, COMPONENT const&, FLOAT*)':
> UDPasp_PortType.cc:(.text+0xb94): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP const&)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::send(UDPasp__Types::ASP__UDP__message const&, COMPONENT const&, FLOAT*)':
> UDPasp_PortType.cc:(.text+0xf46): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__message const&)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::outgoing_public_send(UDPasp__Types::ASP__UDP__open const&)':
> UDPasp_PortType.cc:(.text+0x13ff): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__open const&)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::outgoing_public_send(UDPasp__Types::ASP__UDP__close const&)':
> UDPasp_PortType.cc:(.text+0x1425): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__close const&)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::outgoing_public_send(UDPasp__Types::ASP__UDP const&)':
> UDPasp_PortType.cc:(.text+0x144b): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP const&)'
> UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::outgoing_public_send(UDPasp__Types::ASP__UDP__message const&)':
> UDPasp_PortType.cc:(.text+0x1471): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__message const&)'
> UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0x38): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::Event_Handler(fd_set const*, fd_set const*, fd_set const*, double)'
> UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xb0): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::set_parameter(char const*, char const*)'
> UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xd0): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::user_map(char const*)'
> UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xd8): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::user_unmap(char const*)'
> UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xf0): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::user_start()'
> UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xf8): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::user_stop()'
> UDPasp_PortType.o:(.data.rel.ro._ZTIN16UDPasp__PortType10UDPasp__PTE[_ZTIN16UDPasp__PortType10UDPasp__PTE]+0x10): undefined reference to `typeinfo for UDPasp__PortType::UDPasp__PT_PROVIDER'

So if u guys could point out which steps is wrong, that would be amazing.

**Comment by seanwl** [comment]
I was new to ttcn language, just install titan.core and successfully executed the simple system port test on this page https://github.com/eclipse/titan.core/wiki/Simple-TTCN3-Examples, and I planed to run a dns test, but failed many times.
I the result o compiling your demo code, first its said 

> DNS_Mapping.ttcn:22.1-28: error: There is no module with identifier `UDPasp_Types'

then I copy the files in your titan.TestPorts.UDPasp  src page into demo folders and the error is corrected, but came up with a bunch of new errors, states below,
`if g++   -o DNS_Demo DNS_Demo.o DNS_Mapping.o DNS_Types.o UDPasp_PortType.o UDPasp_Types.o  \
-L/home/seanwl/titan.core/Install/lib -lttcn3 \
-L/lib -lcrypto \
-L/home/seanwl/titan.core/Install/lib -lxml2; \
then : ; else /home/seanwl/titan.core/Install/bin/titanver DNS_Demo.o DNS_Mapping.o DNS_Types.o UDPasp_PortType.o UDPasp_Types.o ; exit 1; fi
DNS_Mapping.o: In function `DNS__Mapping::f__DNS__mapping__behaviour()':
DNS_Mapping.cc:(.text+0x6c02): undefined reference to `DNS__Types::dec__PDU__DNS(OCTETSTRING const&)'
DNS_Mapping.cc:(.text+0x6e1a): undefined reference to `DNS__Types::enc__PDU__DNS(DNS__Types::PDU__DNS const&, BOOLEAN const&, BOOLEAN const&)'
DNS_Types.o: In function `DNS__Types::pre_init_module()':
DNS_Types.cc:(.text+0x43144): undefined reference to `DNS__Types::enc__PDU__DNS(DNS__Types::PDU__DNS const&, BOOLEAN const&, BOOLEAN const&)'
DNS_Types.cc:(.text+0x43166): undefined reference to `DNS__Types::dec__PDU__DNS(OCTETSTRING const&)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::UDPasp__PT(char const*)':
UDPasp_PortType.cc:(.text+0x229): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::UDPasp__PT_PROVIDER(char const*)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::~UDPasp__PT()':
UDPasp_PortType.cc:(.text+0x2a2): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::~UDPasp__PT_PROVIDER()'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::send(UDPasp__Types::ASP__UDP__open const&, COMPONENT const&, FLOAT*)':
UDPasp_PortType.cc:(.text+0x412): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__open const&)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::send(UDPasp__Types::ASP__UDP__close const&, COMPONENT const&, FLOAT*)':
UDPasp_PortType.cc:(.text+0x7e2): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__close const&)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::send(UDPasp__Types::ASP__UDP const&, COMPONENT const&, FLOAT*)':
UDPasp_PortType.cc:(.text+0xb94): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP const&)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::send(UDPasp__Types::ASP__UDP__message const&, COMPONENT const&, FLOAT*)':
UDPasp_PortType.cc:(.text+0xf46): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__message const&)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::outgoing_public_send(UDPasp__Types::ASP__UDP__open const&)':
UDPasp_PortType.cc:(.text+0x13ff): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__open const&)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::outgoing_public_send(UDPasp__Types::ASP__UDP__close const&)':
UDPasp_PortType.cc:(.text+0x1425): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__close const&)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::outgoing_public_send(UDPasp__Types::ASP__UDP const&)':
UDPasp_PortType.cc:(.text+0x144b): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP const&)'
UDPasp_PortType.o: In function `UDPasp__PortType::UDPasp__PT::outgoing_public_send(UDPasp__Types::ASP__UDP__message const&)':
UDPasp_PortType.cc:(.text+0x1471): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::outgoing_send(UDPasp__Types::ASP__UDP__message const&)'
UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0x38): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::Event_Handler(fd_set const*, fd_set const*, fd_set const*, double)'
UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xb0): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::set_parameter(char const*, char const*)'
UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xd0): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::user_map(char const*)'
UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xd8): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::user_unmap(char const*)'
UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xf0): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::user_start()'
UDPasp_PortType.o:(.data.rel.ro._ZTVN16UDPasp__PortType10UDPasp__PTE[_ZTVN16UDPasp__PortType10UDPasp__PTE]+0xf8): undefined reference to `UDPasp__PortType::UDPasp__PT_PROVIDER::user_stop()'
UDPasp_PortType.o:(.data.rel.ro._ZTIN16UDPasp__PortType10UDPasp__PTE[_ZTIN16UDPasp__PortType10UDPasp__PTE]+0x10): undefined reference to `typeinfo for UDPasp__PortType::UDPasp__PT_PROVIDER'
`
So if u guys could point out which steps is wrong, that would be amazing.

**Comment by balaskoa** [comment]
Hi Sean,
you did not copied all necessary files ( _PT.hh/cc files are missing). But I would describe the suggested method:
At the end of page https://github.com/eclipse/titan.core, you can find a list of open source test ports, protocol modules. You can select your necessary protocols. Read the .tpd files for hints about dependencies.
Here is a pseudo command list, pls correct and follow it:
Create  two subfolders TestPorts and ProtocolModules in your git root folder. 
cd TestPorts; 
clone https://github.com/eclipse/titan.TestPorts.UDPasp (correct the syntax)
cd ProtocolModules;
clone https://github.com/eclipse/titan.ProtocolModules.DNS 
cd folder DNS/demo;
execute
makefilegen -ft DNS_CNL113429_demo.tpd
It will build the bin folder, the links in it, the Makefile. It is based in the info collected in the tpd file.
Go to the bin folder; make; run your app as you have learnt from the examples.

I would suggest to use the eclipse titan forum: https://www.eclipse.org/forums/index.php?t=thread&frm_id=297

Best regards
Jeno Balasko, Titan Team, Ericsson
Jeno.Balasko@ericsson.com

**Comment by seanwl** [comment]
Thanks for your guidance, definitely don't know what the tpd files do before. 
I will use the forum, great thanks again :)
